import type { Metadata } from 'next';
import localFont from 'next/font/local';
// import { styleText } from 'util';
import './styles/globals.css';
import styles from './layout.module.css';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   weight: '100 900',
// });

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
